package domain

import "errors"

// Errores de negocio. Los handlers los traducen a respuestas HTTP; nunca se filtran detalles internos.
var (
	ErrInvalidEmail           = errors.New("correo inválido")
	ErrInvalidName            = errors.New("nombre inválido")
	ErrPasswordTooShort       = errors.New("la contraseña es demasiado corta")
	ErrPasswordTooLong        = errors.New("la contraseña es demasiado larga")
	ErrPasswordBreached       = errors.New("la contraseña aparece en filtraciones conocidas")
	ErrPasswordIsEmail        = errors.New("la contraseña no puede ser tu correo")
	ErrAdultRequired          = errors.New("debes declarar que eres mayor de 18 años")
	ErrConsentRequired        = errors.New("debes aceptar los términos y la política de privacidad")
	ErrEmailTaken             = errors.New("el correo ya está registrado")
	ErrInvalidCredentials     = errors.New("correo o contraseña incorrectos")
	ErrAccountSuspended       = errors.New("la cuenta está suspendida")
	ErrAccountDeleted         = errors.New("la cuenta fue eliminada")
	ErrNotFound               = errors.New("no encontrado")
	ErrSessionInvalid         = errors.New("sesión inválida o vencida")
	ErrForbidden              = errors.New("no tienes permiso para esta acción")
	ErrTooManyRequests        = errors.New("demasiados intentos, espera un momento")
	ErrCodeInvalid            = errors.New("el código es incorrecto o venció")
	ErrCodeExhausted          = errors.New("agotaste los intentos, pide un código nuevo")
	ErrEmailAlreadyVerified   = errors.New("tu correo ya está verificado")
	ErrCurrentPasswordInvalid = errors.New("la contraseña actual no es correcta")
	ErrRoleNotAssignable      = errors.New("ese rol no lo asigna un administrador")
	ErrSelfLockout            = errors.New("no puedes quitarte el rol de admin ni suspender tu propia cuenta")
	ErrSuspensionReason       = errors.New("indica el motivo de la suspensión")
	ErrInvalidStatus          = errors.New("estado de cuenta inválido")
	ErrTwoFactorRequired      = errors.New("confirma el código que enviamos a tu correo para continuar")
	ErrTwoFactorNotPending    = errors.New("esta sesión no necesita verificación en dos pasos")
	ErrHumanCheckFailed       = errors.New("no pudimos confirmar que eres una persona, inténtalo de nuevo")
	ErrHumanCheckUnavailable  = errors.New("la verificación de seguridad no está disponible, inténtalo en unos minutos")
	ErrOAuthUnavailable       = errors.New("el acceso con Google no está disponible por ahora")
	ErrOAuthState             = errors.New("el inicio con Google venció o no es válido, inténtalo de nuevo")
	ErrOAuthFailed            = errors.New("Google no pudo confirmar tu cuenta, inténtalo de nuevo")
	ErrOAuthEmailUnverified   = errors.New("tu cuenta de Google no tiene el correo verificado")
	ErrOAuthLinkNeedsPassword = errors.New("ya tienes una cuenta con ese correo: inicia sesión con tu contraseña y vincula Google desde tu perfil")
	ErrOAuthSignupRequired    = errors.New("aún no tienes cuenta en Qatu: regístrate con Google aceptando los términos")
	ErrOAuthAlreadyLinked     = errors.New("tu cuenta de Qatu ya está vinculada a otra cuenta de Google")
	ErrInvalidLocation        = errors.New("la ubicación no es válida")
	ErrOutOfCoverage          = errors.New("todavía no llegamos a esa zona; elige tu distrito de la lista")
	ErrInvalidVertical        = errors.New("tipo de catálogo desconocido")
	ErrInvalidSlug            = errors.New("el identificador solo admite minúsculas, números y guiones")
	ErrInvalidDescription     = errors.New("la descripción es demasiado larga")
	ErrInvalidIcon            = errors.New("el ícono debe ser un nombre de lucide-react, por ejemplo HardHat")
	ErrInvalidRisk            = errors.New("el nivel de riesgo debe ser low, medium o high")
	ErrInvalidSortOrder       = errors.New("el orden debe ser un número entre 0 y 32767")
	ErrInvalidSchema          = errors.New("el esquema de atributos no es un JSON Schema válido")
	ErrSlugTaken              = errors.New("ya existe una categoría con ese identificador en esta vertical")
	ErrCategoryTree           = errors.New("el catálogo tiene 2 niveles: el padre debe ser una raíz de la misma vertical y sin padre")
	ErrUnknownSetting         = errors.New("ajuste desconocido")
	ErrInvalidSettingValue    = errors.New("valor inválido para este ajuste")
	ErrSettingMissing         = errors.New("falta el valor global de un ajuste")
	ErrInvalidUbigeo          = errors.New("el ubigeo del INEI tiene 4 dígitos en la ciudad y 6 en el distrito, que empiezan con los de su ciudad")
	ErrCityTaken              = errors.New("ya existe una ciudad con ese identificador o ubigeo")
	ErrZoneTaken              = errors.New("ya existe un distrito con ese identificador o ubigeo")
	ErrInvalidBoundary        = errors.New("el límite debe ser un Polygon o MultiPolygon GeoJSON válido (lng, lat)")
	ErrZoneFarFromCity        = errors.New("el límite queda lejos de la ciudad: revisa que las coordenadas estén en orden longitud, latitud")
	ErrZoneOverlap            = errors.New("el límite se superpone con otro distrito de la ciudad")
	ErrCityWithoutZones       = errors.New("agrega al menos un distrito activo antes de encender la ciudad")
)

// Publicaciones de herramientas (feature 003).
var (
	ErrLenderProfileRequired   = errors.New("activa tu perfil de arrendador para publicar")
	ErrLenderPhone             = errors.New("escribe un celular peruano de 9 dígitos que empiece con 9")
	ErrLenderBusinessName      = errors.New("escribe el nombre de tu negocio (2 a 80 caracteres)")
	ErrLenderEmailUnverified   = errors.New("confirma tu correo antes de activar tu perfil de arrendador")
	ErrLenderTermsRequired     = errors.New("acepta las condiciones de arrendador para continuar")
	ErrListingTitle            = errors.New("el título debe tener entre 5 y 80 caracteres")
	ErrListingText             = errors.New("la descripción y las instrucciones tienen como máximo 2000 caracteres")
	ErrListingAccessories      = errors.New("hasta 30 accesorios de 80 caracteres como máximo")
	ErrListingAmount           = errors.New("revisa los montos: no pueden ser negativos ni pasar de S/ 100 000")
	ErrListingBookingMode      = errors.New("el modo de reserva debe ser por solicitud o inmediata")
	ErrListingCancelPolicy     = errors.New("la política de cancelación debe ser flexible, moderada o estricta")
	ErrListingVerification     = errors.New("el nivel de verificación mínimo no es válido")
	ErrListingDurations        = errors.New("revisa la antelación y la duración mínima y máxima")
	ErrListingAttributes       = errors.New("los datos de la herramienta no cumplen lo que pide su categoría")
	ErrListingCategory         = errors.New("elige un tipo de herramienta activo del catálogo")
	ErrListingProhibited       = errors.New("esa categoría no se puede publicar en Qatu")
	ErrListingDayPrice         = errors.New("el precio por día es obligatorio")
	ErrListingReplacementValue = errors.New("indica el valor de reposición de la herramienta")
	ErrListingDeposit          = errors.New("la garantía está fuera del rango permitido para este valor y categoría")
	ErrListingFulfillment      = errors.New("ofrece recojo, delivery o ambos")
	ErrListingPickupLocation   = errors.New("marca en el mapa el punto de recojo dentro de una zona atendida")
	ErrListingDeliveryZones    = errors.New("elige al menos un distrito para el delivery")
	ErrListingPhotos           = errors.New("sube al menos 3 fotos de la herramienta")
	ErrListingTransition       = errors.New("la publicación no admite ese cambio en su estado actual")
	ErrListingNotEditable      = errors.New("la publicación no se puede editar en su estado actual")
	ErrListingVersion          = errors.New("la publicación cambió mientras la editabas; recarga para ver la versión actual")
	ErrRejectionReason         = errors.New("escribe el motivo del rechazo (hasta 500 caracteres)")
	ErrAvailabilityOverlap     = errors.New("esas fechas se cruzan con otro bloqueo o reserva")
	ErrAvailabilityPeriod      = errors.New("el periodo no es válido: el fin debe ser después del inicio")
	ErrListingCategoryLocked   = errors.New("la categoría no se cambia después de publicar: duplica la publicación y elige otra")
	ErrListingOwnerLocation    = errors.New("tu perfil de arrendador está en un distrito que ya no atendemos: actualízalo")
	ErrPhotoType               = errors.New("sube una foto JPG, PNG o WebP de hasta 10 MB")
	ErrPhotoLimit              = errors.New("una publicación tiene hasta 12 fotos")
	ErrPhotoNotUploaded        = errors.New("la foto no terminó de subirse; vuelve a intentarlo")
	ErrPhotoInvalid            = errors.New("no pudimos leer esa imagen; prueba con otra foto")
	ErrPhotoOrder              = errors.New("el orden debe incluir cada foto pública una sola vez")
)
