package domain

import "errors"

// Errores de negocio. Los handlers los traducen a respuestas HTTP; nunca se filtran detalles internos.
var (
	ErrInvalidEmail           = errors.New("correo inválido")
	ErrInvalidName            = errors.New("nombre inválido")
	ErrPasswordTooShort       = errors.New("la contraseña es demasiado corta")
	ErrPasswordTooLong        = errors.New("la contraseña es demasiado larga")
	ErrPasswordBreached       = errors.New("la contraseña aparece en filtraciones conocidas")
	ErrPasswordIsEmail        = errors.New("la contraseña no puede ser tu correo")
	ErrAdultRequired          = errors.New("debes declarar que eres mayor de 18 años")
	ErrConsentRequired        = errors.New("debes aceptar los términos y la política de privacidad")
	ErrEmailTaken             = errors.New("el correo ya está registrado")
	ErrInvalidCredentials     = errors.New("correo o contraseña incorrectos")
	ErrAccountSuspended       = errors.New("la cuenta está suspendida")
	ErrAccountDeleted         = errors.New("la cuenta fue eliminada")
	ErrNotFound               = errors.New("no encontrado")
	ErrSessionInvalid         = errors.New("sesión inválida o vencida")
	ErrForbidden              = errors.New("no tienes permiso para esta acción")
	ErrTooManyRequests        = errors.New("demasiados intentos, espera un momento")
	ErrCodeInvalid            = errors.New("el código es incorrecto o venció")
	ErrCodeExhausted          = errors.New("agotaste los intentos, pide un código nuevo")
	ErrEmailAlreadyVerified   = errors.New("tu correo ya está verificado")
	ErrCurrentPasswordInvalid = errors.New("la contraseña actual no es correcta")
	ErrRoleNotAssignable      = errors.New("ese rol no lo asigna un administrador")
	ErrSelfLockout            = errors.New("no puedes quitarte el rol de admin ni suspender tu propia cuenta")
	ErrSuspensionReason       = errors.New("indica el motivo de la suspensión")
	ErrInvalidStatus          = errors.New("estado de cuenta inválido")
	ErrTwoFactorRequired      = errors.New("confirma el código que enviamos a tu correo para continuar")
	ErrTwoFactorNotPending    = errors.New("esta sesión no necesita verificación en dos pasos")
	ErrHumanCheckFailed       = errors.New("no pudimos confirmar que eres una persona, inténtalo de nuevo")
	ErrHumanCheckUnavailable  = errors.New("la verificación de seguridad no está disponible, inténtalo en unos minutos")
	ErrOAuthUnavailable       = errors.New("el acceso con Google no está disponible por ahora")
	ErrOAuthState             = errors.New("el inicio con Google venció o no es válido, inténtalo de nuevo")
	ErrOAuthFailed            = errors.New("Google no pudo confirmar tu cuenta, inténtalo de nuevo")
	ErrOAuthEmailUnverified   = errors.New("tu cuenta de Google no tiene el correo verificado")
	ErrOAuthLinkNeedsPassword = errors.New("ya tienes una cuenta con ese correo: inicia sesión con tu contraseña y vincula Google desde tu perfil")
	ErrOAuthSignupRequired    = errors.New("aún no tienes cuenta en Qatu: regístrate con Google aceptando los términos")
	ErrOAuthAlreadyLinked     = errors.New("tu cuenta de Qatu ya está vinculada a otra cuenta de Google")
	ErrInvalidLocation        = errors.New("la ubicación no es válida")
	ErrOutOfCoverage          = errors.New("todavía no llegamos a esa zona; elige tu distrito de la lista")
	ErrInvalidVertical        = errors.New("tipo de catálogo desconocido")
)
